Some fixes for compilation errors and warnings on different platforms.
Fix for redefinition of variables in nested scope;
Fix fatal error: 'malloc.h' file not found on MacOS;
Fix for the following warnings on Linux:
- unused variable;
- suggest parentheses around '&&' within '||';
- comparison between signed and unsigned integer expressions;
- deleting object of polymorphic class type 'CDelaBella' which has non-virtual destructor might cause undefined behaviour.